#!/bin/bash
set -u -e -E

: ${1:?no box given?}

BOXES=$@

[[ $1 == "_all" ]] && BOXES=$(find boxes -maxdepth 1 -mindepth 1 -type d)

for BOX in $BOXES; do
    echo
    echo "-- destroying $BOX"
    (
        cd $BOX
        vagrant destroy -f || :
        rm -rf Vagrantfile* postinstall* init-root* ip provision*
        echo "---- remaining resources after destroy:"
        ls -l
    )
done

