#!/bin/bash
set -u -e -E -C -o pipefail

[[ $(id -u) == 0 ]] || {
    echo "you need to be root to run this script."
    exit 1
}

HOSTNAME=$(hostname -s)
PUB_KEY=$(ls -1 /vagrant/*.pub)
USERNAME=$(basename $PUB_KEY .pub)

echo "-- initializing environment/repos"
cp -r /vagrant/root/* /

echo
echo "-- adding user/group"
groupadd admins || :
adduser -G admins $USERNAME || :
echo vagrant | sudo passwd --stdin $USERNAME
echo "---- when everything goes wrong: the password of $USERNAME is 'vagrant'"

echo
echo "-- configuring passwordless ssh access"
SSH_DIR=/home/$USERNAME/.ssh
AUTH_KEYS=$SSH_DIR/authorized_keys
mkdir -p $SSH_DIR && chmod 700 $SSH_DIR
touch $AUTH_KEYS
chmod 400 $AUTH_KEYS
cat $PUB_KEY >> $AUTH_KEYS
chown -R $USERNAME $SSH_DIR

echo
echo "-- applying custom postinstall scripts"
for SCRIPT in /vagrant/postinstall/*; do
    [[ -x $SCRIPT ]] || continue
    echo "---- applying $SCRIPT"
    $SCRIPT
done

echo "done."
