#!/bin/bash
set -u -e -E -C -o pipefail

[[ $(id -u) == 0 ]] || {
    echo "you need to be root to run this script."
    exit 1
}

USERNAME=${1:?USERNAME not set!}
shift
ROLES=$*
[[ -z $ROLES ]] && ROLES=yadtclient
HOSTNAME=$(hostname -s)
PUB_KEY=/vagrant/vagrant.pub

echo "-- initializing environment/repos"
cp -r /vagrant/init-root/* /

[[ -f /etc/profile.d/proxy_env.sh ]] && source /etc/profile.d/proxy_env.sh

echo
echo "-- adding user/group"
echo "---- username: $USERNAME"
groupadd admins || :
adduser -G admins $USERNAME || :
echo vagrant | sudo passwd --stdin $USERNAME
#echo "---- when everything goes wrong: the password of $USERNAME is 'vagrant'"
echo "--- username: vagrant"
usermod -a -G admins vagrant

echo
echo "-- configuring passwordless ssh access"
SSH_DIR=/home/$USERNAME/.ssh
AUTH_KEYS=$SSH_DIR/authorized_keys
mkdir -p $SSH_DIR && chmod 700 $SSH_DIR
touch $AUTH_KEYS
chmod 600 $AUTH_KEYS
cat $PUB_KEY >> $AUTH_KEYS
chown -R $USERNAME $SSH_DIR

echo
echo  "-- modifying /etc/hosts"
rm -f /etc/hosts && ln -s /vagrant/hosts /etc/hosts

echo
echo "-- applying custom postinstall scripts"
for STAGE in all $ROLES; do
    echo "---- postinstall stage $STAGE"
    for SCRIPT in /vagrant/postinstall/$STAGE/*; do
        [[ -x $SCRIPT ]] || continue
        echo "------ applying $SCRIPT"
        $SCRIPT $USERNAME
    done
done

echo "done."
